name: meeting_planner
description: meeting_planner

publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  lazy_paginated_data_table: ^0.0.7
  permission_handler: any
  font_awesome_flutter: ^10.4.0
  path_provider: ^2.0.14
  device_preview: ^1.1.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.0
  html_editor_enhanced: ^2.5.1
  flutter_downloader: ^1.10.2
  infinite_scroll_list_view_2: ^1.0.1
  http_error_handler: ^0.0.1
  devicelocale: ^0.7.0
  json_annotation: ^4.8.1
  universal_html: ^2.2.4
  flutter_responsive_tools: ^0.0.1
  gap: ^3.0.1
  fluro: ^2.0.5
  dart_jsonwebtoken: ^2.13.0
  horizontal_data_table: ^4.3.1
  day_night_time_picker: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.13.1
  build_runner: any
  retrofit: ^3.0.1
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  generate: true
